### ISSUE TITLE
centrifuge :: which repo infphilo or DaehwanKimLab

### ISSUE THREAD

**Issue by EricDeveaud** [GuilhemRoyer/PlaScope#2]
Hello, 

documentation points out that centrifguge is requested, and points to 
[inphiloggit hub URL](https://github.com/infphilo/centrifuge) which is a fork of [DaehwanKimLab centrifuge repo](https://github.com/DaehwanKimLab/centrifuge)

any reason for this ?

regards

**Comment by dvallenet** [comment]
Hi,
No reason just a mistake.
The README is now corrected.

**Comment by duboism** [comment]
Just to clarify things:

  - Centrifuge project page is http://www.ccb.jhu.edu/software/centrifuge/; we changed PlaScope documentation to point to this page (see 965ca7714ab541e2ff41c432f357213f857a30db).
  - This page links to https://github.com/infphilo/centrifuge; however, this repo seems outdated.
  - The main repo seems to be https://github.com/DaehwanKimLab/centrifuge (so Centrifuge project page should be updated)

**Comment by EricDeveaud** [comment]
thanks for the clarification.

**Comment by duboism** [comment]
Daehwan Kim confirmed that the main repo is https://github.com/DaehwanKimLab/centrifuge and updated the page at http://www.ccb.jhu.edu/software/centrifuge/.
